import { BlockchainNetworks } from '../types/BlockchainNetworks'

export const BLOCKCHAIN_NETWORKS: BlockchainNetworks = {
  1: {
    name: 'Ethereum',
    logoUri: '/assets/logo/logo_chainid_1_ethereum.svg',
    explorerName: 'etherscan',
    url: 'https://etherscan.io',
    addressPath: '/address/__ADDR__',
    tokenPath: '/token/__ADDR__',
    txPath: '/tx/__HASH__',
    openseaUrl: 'https://opensea.io',
    openseaContractPath: '/assets/ethereum/__ADDR__',
    openseaTokenPath: '/assets/ethereum/__ADDR__/__TOKEN__',
    testnet: false,
  },
  5: {
    name: 'Goerli',
    logoUri: '/assets/logo/logo_chainid_5_goerli.svg',
    explorerName: 'goerli etherscan',
    url: 'https://goerli.etherscan.io',
    addressPath: '/address/__ADDR__',
    tokenPath: '/token/__ADDR__?a=__TOKEN__',
    txPath: '/tx/__HASH__',
    openseaUrl: 'https://opensea.io',
    openseaContractPath: '/assets/goerli/__ADDR__',
    openseaTokenPath: '/assets/goerli/__ADDR__/__TOKEN__',
    testnet: true,
  },
  10: {
    name: 'Optimism',
    logoUri: '/assets/logo/logo_chainid_10_optimism.svg',
    explorerName: 'Optimistic etherscan',
    url: 'https://optimistic.etherscan.io',
    addressPath: '/address/__ADDR__#tokentxnsErc721',
    tokenPath: '/token/__ADDR__?a=__TOKEN__',
    txPath: '/tx/__HASH__',
    openseaUrl: 'https://opensea.io',
    openseaContractPath: '/assets/optimism/__ADDR__',
    openseaTokenPath: '/assets/optimism/__ADDR__/__TOKEN__',
    testnet: false,
  },
  137: {
    name: 'Polygon',
    logoUri: '/assets/logo/logo_chainid_137_polygon.svg',
    explorerName: 'polygonscan',
    url: 'https://polygonscan.com',
    addressPath: '/address/__ADDR__',
    tokenPath: '/token/__ADDR__',
    txPath: '/tx/__HASH__',
    openseaUrl: 'https://opensea.io',
    openseaContractPath: '/assets/matic/__ADDR__',
    openseaTokenPath: '/assets/matic/__ADDR__/__TOKEN__',
    testnet: false,
  },
  // 250: {
  //   name: 'Fantom',
  //   logoUri: '/assets/logo/logo_chainid_250_fantom.svg',
  //   explorerName: 'FtmScan',
  //   url: 'https://ftmscan.com',
  //   addressPath: '/address/__ADDR__',
  //   tokenPath: '/token/__ADDR__',
  //   testnet: false,
  // },
  420: {
    name: 'Optimism Goerli Testnet',
    logoUri: '/assets/logo/logo_chainid_420_optimism-goerli-testnet.svg',
    explorerName: 'Optimism Goerli Etherscan',
    url: 'https://goerli-optimism.etherscan.io',
    addressPath: '/address/__ADDR__',
    tokenPath: '/token/__ADDR__?a=__TOKEN__',
    txPath: '/tx/__HASH__',
    openseaUrl: 'https://testnets.opensea.io',
    openseaContractPath: '/assets/optimism-goerli/__ADDR__',
    openseaTokenPath: '/assets/optimism-goerli/__ADDR__/__TOKEN__',
    testnet: true,
  },
  // 4002: {
  //   name: 'Fantom Testnet',
  //   logoUri: '/assets/logo/logo_chainid_4002_fantom-testnet.svg',
  //   explorerName: 'FTMScan testnet',
  //   url: 'https://testnet.ftmscan.com',
  //   addressPath: '/address/__ADDR__',
  //   tokenPath: '/token/__ADDR__',
  //   testnet: true,
  // },
  // 42161: {
  //   name: 'Arbitrum',
  //   logoUri: '/assets/logo/logo_chainid_42161_arbitrum.svg',
  //   explorerName: 'Arbiscan',
  //   url: 'https://arbiscan.io',
  //   addressPath: '/address/__ADDR__',
  //   tokenPath: '/token/__ADDR__',
  //   testnet: false,
  // },
  80001: {
    name: 'Matic Testnet Mumbai',
    logoUri: '/assets/logo/logo_chainid_80001_munbai.svg',
    explorerName: 'munbai polygonscan',
    url: 'https://mumbai.polygonscan.com',
    addressPath: '/address/__ADDR__',
    tokenPath: '/token/__ADDR__',
    txPath: '/tx/__HASH__',
    openseaUrl: 'https://testnets.opensea.io',
    openseaContractPath: '/assets/mumbai/__ADDR__',
    openseaTokenPath: '/assets/mumbai/__ADDR__/__TOKEN__',
    testnet: true,
  },
  // 421613: {
  //   name: 'Arbitrum Goerli',
  //   logoUri: '/assets/logo/logo_chainid_421613_arbitrum-goerli.svg',
  //   explorerName: 'Arbitrum Goerli',
  //   url: 'https://goerli.arbiscan.io',
  //   addressPath: '/address/__ADDR__',
  //   tokenPath: '/token/__ADDR__',
  //   testnet: true,
  // },
}
